version: '3.8'

services:
  core-node:
    build: .
    container_name: core-node
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: core-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: corenode
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: core-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
